<template>
  <svg
    version="1.1"
    id="Layer_1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    x="0px"
    y="0px"
    width="16px"
    height="16px"
    viewBox="0 0 16 16"
    enable-background="new 0 0 16 16"
    xml:space="preserve"
  >
    <image
      id="image0"
      width="16"
      height="16"
      x="0"
      y="0"
      href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAJcEhZ
cwAADsQAAA7EAZUrDhsAAAAHdElNRQfoAg8BDCMbcCQwAAAAcklEQVQoz63QwQnCQBBG4U+byE1S
kRAIYi1JHV4ULSjYgtjHRhgve8iGiIfknQbmDTPzswWVQZPrnYurfSk8hZSVXgj3Umkl4eOMg5cQ
HnNl3EA5GYXkiNpbCDfze3/T5vlmsmLyy7p2GVS3FNTfqNfxBWflQ5kQ3NDTAAAAJXRFWHRkYXRl
OmNyZWF0ZQAyMDI0LTAyLTE1VDAxOjEyOjM1KzAwOjAwHSwbagAAACV0RVh0ZGF0ZTptb2RpZnkA
MjAyNC0wMi0xNVQwMToxMjozNSswMDowMGxxo9YAAAAZdEVYdFNvZnR3YXJlAHd3dy5pbmtzY2Fw
ZS5vcmeb7jwaAAAAAElFTkSuQmCC"
    />
  </svg>
</template>
