<template>
  <svg
    version="1.1"
    id="Layer_1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    x="0px"
    y="0px"
    width="16px"
    height="16px"
    viewBox="0 0 16 16"
    enable-background="new 0 0 16 16"
    xml:space="preserve"
  >
    <image
      id="image0"
      width="16"
      height="16"
      x="0"
      y="0"
      href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAJcEhZ
cwAADsQAAA7EAZUrDhsAAAAHdElNRQfoAg8DDCMY9PBeAAAAcUlEQVQoz63QwQnCUBBF0fNtwq3Y
jhCICxfaiX2okGBDkh6CXchXGDeBr24Mmrsb7jBveEzJTOMgDVPtYv6uz0LYDzoLXdHJSQhXS6xl
4WH7l96V860QegtUsnC3Ka+NIDm+RKzcPiOmWvlS1Iiqf+UJxXJDlxDxOPwAAAAldEVYdGRhdGU6
Y3JlYXRlADIwMjQtMDItMTVUMDI6MTI6MzUrMDE6MDAYWhDBAAAAJXRFWHRkYXRlOm1vZGlmeQAy
MDI0LTAyLTE1VDAyOjEyOjM1KzAxOjAwaQeofQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBl
Lm9yZ5vuPBoAAAAASUVORK5CYII="
    />
  </svg>
</template>
